id: P000417
initial_creation_type: ocr
created_at: 21/03/2020
last_modified_at: 2021-12-16 15:38:53.307706
source_metadata:
  id: bdr:W00KG0619
  title: བོད་ཀྱི་རྩོམ་ལུས་རྣམ་བཤད
  author: ''
  volumes:
    8264f5458a154d2b96e279d898bffb0f:
      image_group_id: I4CZ354566
      title: Volume 1 of bod kyi rtsom lus rnam bshad
      volume_number: 1
      total_pages: 232
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: true
